import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomeComponents from "./home/page";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="container flex justify-between max-w-[800px] m-auto">
        <Link href={"/home"}>
          <div>Home</div>
        </Link>
        <Link href={"/main"}>
          <div>Main</div>
        </Link>
        <Link href={"/about"}>
          <div>About My</div>
        </Link>
      </div>
        {children}
      </body>
    </html>
  );
}
