import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ParticleCanvas from "./loading/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container  text-4xl flex justify-between max-w-[800px] m-auto">
          <Link href={"/home"}>
            <div>Home</div>
          </Link>
          <Link href={"/about"}>
            <div>About Me</div>
          </Link>{" "}
          <Link href={"/profil"}>
            <div>Projekts</div>
          </Link>
          <Link href={"/contakt"}>
            <div>Contakt</div>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
